export const mockData = [
  {
    id: 1,
    jobId: "1000001958",
    name: "John Mwangi",
    source: "SmartCheck",
    date: "23/01/26",
    timestamp: "11:05:42",
    jobTime: "0s",
    product: "AML",
    productSub: "aml_type_10",
    idType: "-",
    country: "KE",
    result: "Not found on list",
    message: "Not found on list",
  },
  {
    id: 2,
    jobId: "1000001957",
    name: "Acme Corp Ltd",
    source: "SmartCheck",
    date: "23/01/26",
    timestamp: "09:46:06",
    jobTime: "1s",
    product: "Business Verification",
    productSub: "",
    idType: "BUSINESS_REGISTRATION",
    country: "KE",
    result: "Approved",
    message: "Business Verified",
  },
  {
    id: 3,
    jobId: "1000001955",
    name: "Sarah Wanjiku",
    source: "SmartCheck",
    date: "22/01/26",
    timestamp: "20:43:45",
    jobTime: "2s",
    product: "AML",
    productSub: "aml_type_10",
    idType: "-",
    country: "KE",
    result: "Not found on list",
    message: "Not found on list",
  },
  {
    id: 4,
    jobId: "1000001954",
    name: "Peter Ochieng",
    source: "rest_api",
    date: "22/01/26",
    timestamp: "12:57:58",
    jobTime: "1s",
    product: "Enhanced KYC",
    productSub: "aml_type_5",
    idType: "NATIONAL_ID",
    country: "KE",
    result: "Approved",
    message: "ID Number Validated",
  },
  {
    id: 5,
    jobId: "1000001953",
    name: "Grace Akinyi",
    source: "rest_api",
    date: "22/01/26",
    timestamp: "12:57:58",
    jobTime: "2s",
    product: "Enhanced KYC",
    productSub: "aml_type_5",
    idType: "NATIONAL_ID",
    country: "KE",
    result: "Approved",
    message: "ID Number Validated",
  },
  {
    id: 6,
    jobId: "1000001952",
    name: "David Kimani",
    source: "rest_api",
    date: "22/01/26",
    timestamp: "12:57:58",
    jobTime: "1s",
    product: "Enhanced KYC",
    productSub: "aml_type_5",
    idType: "NATIONAL_ID",
    country: "KE",
    result: "Approved",
    message: "ID Number Validated",
  },
  {
    id: 7,
    jobId: "1000001951",
    name: "Mary Njeri",
    source: "rest_api",
    date: "22/01/26",
    timestamp: "12:57:55",
    jobTime: "2s",
    product: "Enhanced KYC",
    productSub: "aml_type_5",
    idType: "NATIONAL_ID",
    country: "KE",
    result: "Approved",
    message: "ID Number Validated",
  },
  {
    id: 8,
    jobId: "1000001950",
    name: "James Otieno",
    source: "rest_api",
    date: "21/01/26",
    timestamp: "20:13:32",
    jobTime: "1s",
    product: "Enhanced KYC",
    productSub: "aml_type_5",
    idType: "NATIONAL_ID",
    country: "KE",
    result: "Approved",
    message: "ID Number Validated",
  },
  {
    id: 9,
    jobId: "1000001949",
    name: "Faith Wambui",
    source: "rest_api",
    date: "21/01/26",
    timestamp: "20:13:30",
    jobTime: "2s",
    product: "Enhanced KYC",
    productSub: "aml_type_5",
    idType: "NATIONAL_ID",
    country: "KE",
    result: "Approved",
    message: "ID Number Validated",
  },
  {
    id: 10,
    jobId: "1000001948",
    name: "Michael Kipchoge",
    source: "rest_api",
    date: "21/01/26",
    timestamp: "20:13:29",
    jobTime: "1s",
    product: "Enhanced KYC",
    productSub: "aml_type_5",
    idType: "NATIONAL_ID",
    country: "KE",
    result: "Approved",
    message: "ID Number Validated",
  },
];
